//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FarmEntities : DbContext
    {
        public FarmEntities()
            : base("name=FarmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int AddHarvestedQuantityByWorker(Nullable<double> quantity, string username, string workername)
        {
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("quantity", quantity) :
                new ObjectParameter("quantity", typeof(double));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var workernameParameter = workername != null ?
                new ObjectParameter("workername", workername) :
                new ObjectParameter("workername", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddHarvestedQuantityByWorker", quantityParameter, usernameParameter, workernameParameter);
        }
    
        public virtual int AddPlantation(string harvest, Nullable<int> plantationID)
        {
            var harvestParameter = harvest != null ?
                new ObjectParameter("Harvest", harvest) :
                new ObjectParameter("Harvest", typeof(string));
    
            var plantationIDParameter = plantationID.HasValue ?
                new ObjectParameter("PlantationID", plantationID) :
                new ObjectParameter("PlantationID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddPlantation", harvestParameter, plantationIDParameter);
        }
    
        public virtual int AddUser(string username, string password, string name, string cNP, string addess, string email, Nullable<int> userID)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var cNPParameter = cNP != null ?
                new ObjectParameter("CNP", cNP) :
                new ObjectParameter("CNP", typeof(string));
    
            var addessParameter = addess != null ?
                new ObjectParameter("Addess", addess) :
                new ObjectParameter("Addess", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddUser", usernameParameter, passwordParameter, nameParameter, cNPParameter, addessParameter, emailParameter, userIDParameter);
        }
    
        public virtual int AddWorker(string workername)
        {
            var workernameParameter = workername != null ?
                new ObjectParameter("workername", workername) :
                new ObjectParameter("workername", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddWorker", workernameParameter);
        }
    
        public virtual int DeletePlantation(Nullable<int> plantationID)
        {
            var plantationIDParameter = plantationID.HasValue ?
                new ObjectParameter("PlantationID", plantationID) :
                new ObjectParameter("PlantationID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeletePlantation", plantationIDParameter);
        }
    
        public virtual int DeleteUser(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteUser", usernameParameter);
        }
    
        public virtual int DeleteWorker(string workerName)
        {
            var workerNameParameter = workerName != null ?
                new ObjectParameter("WorkerName", workerName) :
                new ObjectParameter("WorkerName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteWorker", workerNameParameter);
        }
    
        public virtual ObjectResult<GetAllPlantations_Result> GetAllPlantations()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllPlantations_Result>("GetAllPlantations");
        }
    
        public virtual ObjectResult<GetAllUsers_Result> GetAllUsers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllUsers_Result>("GetAllUsers");
        }
    
        public virtual ObjectResult<string> GetAllWorkers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetAllWorkers");
        }
    
        public virtual ObjectResult<GetPlantationByUserID_Result> GetPlantationByUserID(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPlantationByUserID_Result>("GetPlantationByUserID", userIDParameter);
        }
    
        public virtual ObjectResult<GetQuantitiesByWorker_Result> GetQuantitiesByWorker(string workerName)
        {
            var workerNameParameter = workerName != null ?
                new ObjectParameter("WorkerName", workerName) :
                new ObjectParameter("WorkerName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetQuantitiesByWorker_Result>("GetQuantitiesByWorker", workerNameParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> GetTotalQuantityByWorker(string workerName)
        {
            var workerNameParameter = workerName != null ?
                new ObjectParameter("WorkerName", workerName) :
                new ObjectParameter("WorkerName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("GetTotalQuantityByWorker", workerNameParameter);
        }
    
        public virtual ObjectResult<GetUserByUsernameAndPassword_Result> GetUserByUsernameAndPassword(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserByUsernameAndPassword_Result>("GetUserByUsernameAndPassword", usernameParameter, passwordParameter);
        }
    
        public virtual int UpdatePlantation(Nullable<int> plantationID, string harvest)
        {
            var plantationIDParameter = plantationID.HasValue ?
                new ObjectParameter("PlantationID", plantationID) :
                new ObjectParameter("PlantationID", typeof(int));
    
            var harvestParameter = harvest != null ?
                new ObjectParameter("Harvest", harvest) :
                new ObjectParameter("Harvest", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdatePlantation", plantationIDParameter, harvestParameter);
        }
    
        public virtual int UpdateUser(Nullable<int> userID, string username, string password, string name, string cNP, string addess, string email)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var cNPParameter = cNP != null ?
                new ObjectParameter("CNP", cNP) :
                new ObjectParameter("CNP", typeof(string));
    
            var addessParameter = addess != null ?
                new ObjectParameter("Addess", addess) :
                new ObjectParameter("Addess", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateUser", userIDParameter, usernameParameter, passwordParameter, nameParameter, cNPParameter, addessParameter, emailParameter);
        }
    }
}
